# TODO: replace the title with the name of your restaurant!
title: "Nails by Pear's House"
# TODO: write your restaurateur alter ego name below, or your own name
author: Chi Le
# TODO: write your Google Analytics tracking ID below
google_analytics: G-GVS377QQ3H


theme: minima

collections:
  explorations:
    output: true
